name: Release Qwik City

on:
  workflow_dispatch:
    inputs:
      disttag:
        description: 'Publish "@builder.io/qwik-city" to NPM using this dist-tag. The version number will come from version found in package.json.'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - next
          - latest

jobs:
  publish:
    name: 'Release @builder.io/qwik-city'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/

      - run: corepack enable

      - name: Install NPM Dependencies
        run: pnpm install --frozen-lockfile

      - name: Test Qwik City
        run: cd packages/qwik-city && pnpm test

      - name: Build Qwik City
        run: cd packages/qwik-city && pnpm build

      - name: Publish Qwik City
        run: cd packages/qwik-city && pnpm tsm scripts/release.ts --set-dist-tag="${{ github.event.inputs.disttag }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
